### ISSUE TITLE
Will not start -- jQuery is not defined or Module did not self-register

### ISSUE THREAD

**Issue by scottmessinger** [tildeio/ember-cli-fastboot#64]
Hi!

I'm trying to get ember fastboot up and running and I can't manage to get ember cli to even boot. Here's the repo https://github.com/scottmessinger/ember-fastboot-demo and here are the errors I'm seeing: 

**With Node 0.10.32**
```
Future versions of Ember CLI will not support v0.10.32. Please update to Node 0.12 or io.js.
version: 1.13.8
Built project successfully. Stored in "fastboot-dist".
DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead.
DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead.
DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead.
jQuery is not defined
ReferenceError: jQuery is not defined
    at <anonymous>:64348:41
    at <anonymous>:64349:3
    at Object.Contextify.sandbox.run (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli-fastboot/node_modules/contextify/lib/contextify.js:12:24)
    at new EmberApp (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli-fastboot/lib/models/ember-app.js:29:11)
    at new FastBootServer (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli-fastboot/lib/models/server.js:7:14)
    at Class.module.exports.runCommand (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli-fastboot/lib/commands/fastboot.js:21:18)
    at Class.<anonymous> (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli-fastboot/lib/commands/fastboot.js:72:19)
    at lib$rsvp$$internal$$tryCatch (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
```

**With iojs***
```
teachnow:mervo scottmessinger$ nvm use iojs
Now using io.js v2.4.0 (npm v2.13.0)
teachnow:mervo scottmessinger$ ember fastboot
version: 1.13.8
Built project successfully. Stored in "fastboot-dist".
Module did not self-register.
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli-fastboot/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli-fastboot/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
```

**With Node 0.12.7**
```
teachnow:mervo scottmessinger$ nvm use 0.12
Now using node v0.12.7 (npm v2.11.3)
teachnow:mervo scottmessinger$ ember fastboot
version: 1.13.8
Built project successfully. Stored in "fastboot-dist".
Module did not self-register.
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli-fastboot/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/scottmessinger/code/commoncurriculum/mervo/node_modules/ember-cli-fastboot/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by rwjblue** [comment]
There are known issues with iojs (I spoke with @tomdale about this a few days ago), but I believe that https://github.com/ember-cli/ember-cli-shims/pull/30 will resolve the issue you pasted for Node 0.10.

**Comment by scottmessinger** [comment]
@rwjblue You're the best! I linked to that [commit](https://github.com/thorsteinsson/ember-cli-shims/commit/0ebaef04357f08172d872fbd59e9534426a40df9) and it worked great. Thanks so much! Do you want to keep this issue up until that change is merged? Or should I close it?

**Comment by wagenet** [comment]
@scottmessinger seems good to keep this open, seeing as I found this one and not the other :)

**Comment by tomdale** [comment]
Should be fixed now, let us know if you're still having issues @scottmessinger
